apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "snyk-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snyk-exporter.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "snyk-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "snyk-exporter.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "snyk-exporter.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: SNYK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "snyk-exporter.secretName" . }}
                  key: api-token
            {{- with .Values.extraEnv }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          args:
            - --snyk.api-token=$(SNYK_API_TOKEN)
            - --snyk.api-url={{ .Values.snyk.apiUrl }}
            - --snyk.interval={{ .Values.snyk.interval }}
            - --snyk.timeout={{ .Values.snyk.timeout }}
            - --web.listen-address=:9532
            {{- range .Values.snyk.organizations }}
            - --snyk.organization={{ . }}
            {{- end }}
          ports:
            - name: http
              containerPort: 9532
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.extraVolumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.extraVolumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
