{{- if and (not .Values.snyk.existingSecret) (not .Values.snyk.apiToken) }}
{{- fail "Either snyk.apiToken or snyk.existingSecret must be set" }}
{{- end }}
{{- if and (not .Values.snyk.existingSecret) .Values.snyk.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "snyk-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "snyk-exporter.labels" . | nindent 4 }}
type: Opaque
stringData:
  api-token: {{ .Values.snyk.apiToken | quote }}
{{- end }}
